creep/urls.py
from django.conf.urls import url

from . import views

app_name='my_creep'
urlpatterns = [
    url(r'^movie/$', views.movie,name='creep_mv'),
    url(r'^weather/$', views.weather,name='creep_wea'),
    url(r'^jdphone/$', views.jdphone,name='creep_jd'),
    url(r'^mainPage/$', views.mainPage,name='creep_mainPage')
]

scraping/urls.py
from django.contrib import admin
from django.conf.urls import url, include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^creep/', include('creep.urls',namespace='my_creep')),
]

creep/models.py
from __future__ import unicode_literals
from django.db import models

class Movie(models.Model):
    url = models.TextField(null=True)
    content = models.TextField(null=True)

class Weather(models.Model):
    day = models.TextField(null=True)
    weather = models.TextField(null=True)
    temp = models.TextField(null=True)

class JDphone(models.Model):
    item_page = models.TextField(null=True)
    item_name = models.TextField(null=True)
    item_price = models.TextField(null=True)

creep/views.py
from django.shortcuts import render
from creep import models
from django.shortcuts import render

def movie(request):
    movie_list = models.Movie.objects.all()
    return render(request,'creep/movie.html',{'movie_list':movie_list})

def weather(request):
    weather_list = models.Weather.objects.all()
    return render(request,'creep/weather.html',{'weather_list':weather_list})

def jdphone(request):
    jdphone_list = models.JDphone.objects.all()
    return render(request,'creep/jdphone.html',{'jdphone_list':jdphone_list})

def mainPage(request):
    return render(request,'creep/mainPage.html')

creep/templates/creep/jdphone.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Bootstrap 实例 - 一个简单的网页</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .fakeimg {
            height: 200px;
            background: #aaa;
        }
    </style>
</head>

<body>

    <div class="jumbotron text-center" style="margin-bottom:0">
        <h1>python爬虫</h1>
    </div>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'my_creep:creep_mainPage' %}">主页面</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'my_creep:creep_mv' %}">豆瓣电影爬虫</a></li>
                    <li><a href="{% url 'my_creep:creep_wea' %}">天气爬虫</a></li>
                    <li class="active"><a href="{% url 'my_creep:creep_jd' %}">京东手机爬虫(前10页)</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <div class="jumbotron text-center" style="margin-bottom:0">
            <h1>京东手机爬虫(前10页)</h1>
        </div>

        <div class="jumbotron text-center" style="margin-bottom:0">
            <table>
                <tr>
                    <th style="text-align:center">item_page</th>
                    <th style="text-align:center">item_name</th>
                    <th style="text-align:center">item_price</th>
                </tr>
                {% for line in jdphone_list %}
                <tr>
                    <td>{{line.item_page}}</td>
                    <td>{{line.item_name}}</td>
                    <td>{{line.item_price}}</td>
                </tr>
                {% endfor%}
            </table>
        </div>

    </div>
</body>

</html>

creep/templates/creep/mainPage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Bootstrap 实例 - 一个简单的网页</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .fakeimg {
            height: 200px;
            background: #aaa;
        }
    </style>
</head>

<body>

    <div class="jumbotron text-center" style="margin-bottom:0">
        <h1>python爬虫</h1>
    </div>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'my_creep:creep_mainPage' %}">主页面</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'my_creep:creep_mv' %}">豆瓣电影爬虫</a></li>
                    <li><a href="{% url 'my_creep:creep_wea' %}">天气爬虫</a></li>
                    <li><a href="{% url 'my_creep:creep_jd' %}">京东手机爬虫(前10页)</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <div class="jumbotron text-center" style="margin-bottom:0">
            <h1>主页面</h1>
        </div>

        <div class="jumbotron text-center" style="margin-bottom:0">
            <h1>Hello 爬虫</h1>
        </div>

    </div>
</body>

</html>

creep/templates/creep/movie.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Bootstrap 实例 - 一个简单的网页</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .fakeimg {
            height: 200px;
            background: #aaa;
        }
    </style>
</head>

<body>

    <div class="jumbotron text-center" style="margin-bottom:0">
        <h1>python爬虫</h1>
    </div>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'my_creep:creep_mainPage' %}">主页面</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'my_creep:creep_mv' %}">豆瓣电影爬虫</a></li>
                    <li><a href="{% url 'my_creep:creep_wea' %}">天气爬虫</a></li>
                    <li><a href="{% url 'my_creep:creep_jd' %}">京东手机爬虫(前10页)</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <div class="jumbotron text-center" style="margin-bottom:0">
            <h1>豆瓣爬虫</h1>
        </div>

        <div class="jumbotron text-center" style="margin-bottom:0">
            <table>
                <tr>
                    <th>id</th>
                    <th style="text-align:center">url</th>
                    <th style="text-align:center">content</th>
                </tr>
                {% for line in movie_list %}
                <tr>
                    <td>{{line.id}}</td>
                    <td>{{line.url}}</td>
                    <td>{{line.content}}</td>
                </tr>
                {% endfor%}
            </table>
        </div>

    </div>
</body>

</html>

creep/templates/creep/weather.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Bootstrap 实例 - 一个简单的网页</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .fakeimg {
            height: 200px;
            background: #aaa;
        }
    </style>
</head>

<body>

    <div class="jumbotron text-center" style="margin-bottom:0">
        <h1>python爬虫</h1>
    </div>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'my_creep:creep_mainPage' %}">主页面</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'my_creep:creep_mv' %}">豆瓣电影爬虫</a></li>
                    <li class="active"><a href="{% url 'my_creep:creep_wea' %}">天气爬虫</a></li>
                    <li><a href="{% url 'my_creep:creep_jd' %}">京东手机爬虫(前10页)</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <div class="jumbotron text-center" style="margin-bottom:0">
            <h1>天气爬虫</h1>
        </div>

        <div class="jumbotron text-center" style="margin-bottom:0">
            <table width='850'>
                <tr>
                    <th style="text-align:center">day</th>
                    <th style="text-align:center">weather</th>
                    <th style="text-align:center">temp</th>
                </tr>
                {% for line in weather_list %}
                <tr>
                    <td>{{line.day}}</td>
                    <td>{{line.weather}}</td>
                    <td>{{line.temp}}</td>
                </tr>
                {% endfor%}
            </table>
        </div>

    </div>
</body>

</html>